function(check_file_changed CHECK REF_FILE TIMESTAMP_FILE)
	set(REF_TIMESTAMP_FILE "${CMAKE_CURRENT_BINARY_DIR}/${TIMESTAMP_FILE}.timestamp")

	if(EXISTS ${REF_TIMESTAMP_FILE})
		file(READ ${REF_TIMESTAMP_FILE} OLD_TIMESTAMP)
	else()
		set(OLD_TIMESTAMP "")
	endif()

	file(TIMESTAMP ${REF_FILE} NEW_TIMESTAMP)

	if("${NEW_TIMESTAMP}" STREQUAL "${OLD_TIMESTAMP}")
		set(${CHECK} OFF PARENT_SCOPE)
	else()
		file(WRITE ${REF_TIMESTAMP_FILE} ${NEW_TIMESTAMP})
		set(${CHECK} ON PARENT_SCOPE)
	endif()
endfunction()
